# Generated by Django 4.2.21 on 2025-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_images/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='Avatar/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
